import java.util.Scanner;

class Exception {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        try {
            System.out.println("Enter Numerator:");
            int numerator = sc.nextInt();
            System.out.println("Enter Denominator:");
            int denominator = sc.nextInt();
            int result = divide(numerator, denominator);
            System.out.println("Result=:" + result);
        } catch (ArithmeticException e) {
            System.out.println("Division by zero not allowed!");
        } finally

        {
            System.out.println("Finally block executed");
            sc.close();
        }
    }

    private static int divide(int numerator, int denominator) {
        return numerator / denominator;
    }
}
